# Generated by Django 4.1.1 on 2022-11-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("googleauth", "0003_rename_socailuser_socialuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialuser",
            name="bio",
            field=models.TextField(default=""),
        ),
    ]
