# Generated by Django 4.1.1 on 2022-11-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("googleauth", "0004_socialuser_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassObj",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.TextField(default="")),
                ("catalog_number", models.TextField(default="")),
                ("course_number", models.TextField(default="")),
                ("name", models.TextField(default="")),
                ("email", models.TextField(default="")),
                ("semester_code", models.TextField(default="")),
                ("course_section", models.TextField(default="")),
                ("description", models.TextField(default="")),
                ("units", models.TextField(default="")),
                ("component", models.TextField(default="")),
                ("class_capacity", models.TextField(default="")),
                ("wait_list", models.TextField(default="")),
                ("wait_cap", models.TextField(default="")),
                ("enrollment_total", models.TextField(default="")),
                ("enrollment_available", models.TextField(default="")),
                ("topic", models.TextField(default="")),
                ("days", models.TextField(default="")),
                ("start_time", models.TextField(default="")),
                ("end_time", models.TextField(default="")),
                ("facility_description", models.TextField(default="")),
                ("susers", models.ManyToManyField(to="googleauth.socialuser")),
            ],
        ),
    ]
