# Generated by Django 4.1.1 on 2022-11-09 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("googleauth", "0005_classobj"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialuser",
            name="friends",
            field=models.ManyToManyField(
                related_name="friended_by", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ScheduleComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commentor_name", models.CharField(default="", max_length=50)),
                ("comment", models.TextField(default="")),
                (
                    "comment_poster",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="googleauth.socialuser",
                    ),
                ),
                (
                    "schedule_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_comments",
                        to="googleauth.socialuser",
                    ),
                ),
            ],
        ),
    ]
