# Generated by Django 4.1.1 on 2022-11-09 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("googleauth", "0006_socialuser_friends_schedulecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulecomment",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 9, 0, 0),
                verbose_name="date published",
            ),
        ),
    ]
