# Generated by Django 4.1.2 on 2022-11-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("googleauth", "0007_schedulecomment_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="course_num",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
        migrations.AddField(
            model_name="department",
            name="instructor",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="department",
            name="open_seats",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
