# Generated by Django 4.1.1 on 2022-11-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("googleauth", "0008_department_course_num_department_instructor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="")),
                (
                    "classes",
                    models.ManyToManyField(blank=True, to="googleauth.classobj"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="googleauth.socialuser",
                    ),
                ),
            ],
        ),
    ]
