# Generated by Django 4.1.1 on 2022-11-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("googleauth", "0009_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulecomment",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="googleauth.schedule",
            ),
        ),
    ]
